In [37]:
import pandas as pd 
import numpy as np 

df = pd.read_csv("../data/raw/vehicle_sensor_data.csv")
df.head

<bound method NDFrame.head of     vehicle_id            timestamp  engine_temperature  battery_voltage  \
0        VH002  2026-09-08 09:00:00              107.52            11.90
1        VH003  2026-09-08 09:05:00              103.67            11.74
2        VH005  2026-09-08 09:10:00              106.75            11.50
3        VH001  2026-09-08 09:15:00               92.06            11.96
4        VH002  2026-09-08 09:20:00               96.11            11.76
..         ...                  ...                 ...              ...
995      VH002  2026-09-11 19:55:00              101.84            11.61
996      VH004  2026-09-11 20:00:00               93.96            11.78
997      VH004  2026-09-11 20:05:00               86.37            12.50
998      VH002  2026-09-11 20:10:00               96.67            12.42
999      VH002  2026-09-11 20:15:00              103.66            12.92

     vibration  brake_temperature  speed  mileage fault_code  \
0         3.01              87.31     50    33076       F000
1         4.70              72.66     57    95784       F001
2         4.05              91.00     99    31791       F001
3         6.02              67.53     98    23477       F001
4         4.08              88.42     41    80012       F002
..         ...                ...    ...      ...        ...
995       7.02              64.44     82    55738       F000
996       4.40              98.13     42    74518       F002
997       7.60              60.17     40    50208       F002
998       7.10              99.87     53    37051       F002
999       4.48             101.02     66    34698       F000

    maintenance_required
0                    Yes
1                    Yes
2                    Yes
3                     No
4                     No
..                   ...
995                  Yes
996                   No
997                   No
998                   No
999                  Yes

[1000 rows x 10 columns]>

In [38]:
df.shape

(1000, 10)

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   vehicle_id            1000 non-null   str
 1   timestamp             1000 non-null   str
 2   engine_temperature    1000 non-null   float64
 3   battery_voltage       1000 non-null   float64
 4   vibration             1000 non-null   float64
 5   brake_temperature     1000 non-null   float64
 6   speed                 1000 non-null   int64
 7   mileage               1000 non-null   int64
 8   fault_code            1000 non-null   str
 9   maintenance_required  1000 non-null   str
dtypes: float64(4), int64(2), str(4)
memory usage: 107.9 KB

In [40]:
df.describe()

,engine_temperature,battery_voltage,vibration,brake_temperature,speed,mileage
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,94.821000,12.262650,5.034930,90.342700,61.255000,55567.784000
std,8.636402,0.437194,2.283062,17.089164,23.180149,26074.643126
min,80.060000,11.500000,1.010000,60.110000,20.000000,10020.000000
25%,87.007500,11.880000,3.120000,75.905000,41.750000,33061.500000
50%,94.535000,12.260000,5.045000,90.095000,62.000000,56359.000000
75%,102.290000,12.642500,7.062500,104.837500,82.000000,78617.000000
max,109.970000,13.000000,8.990000,119.980000,100.000000,99976.000000

In [41]:
df.isnull().sum()

vehicle_id              0
timestamp               0
engine_temperature      0
battery_voltage         0
vibration               0
brake_temperature       0
speed                   0
mileage                 0
fault_code              0
maintenance_required    0
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df.dtypes

vehicle_id                  str
timestamp                   str
engine_temperature      float64
battery_voltage         float64
vibration               float64
brake_temperature       float64
speed                     int64
mileage                   int64
fault_code                  str
maintenance_required        str
dtype: object

In [44]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [45]:
df.dtypes

vehicle_id                         str
timestamp               datetime64[us]
engine_temperature             float64
battery_voltage                float64
vibration                      float64
brake_temperature              float64
speed                            int64
mileage                          int64
fault_code                         str
maintenance_required               str
dtype: object

In [46]:
df["maintenance_required"].value_counts()

maintenance_required
No     626
Yes    374
Name: count, dtype: int64

In [47]:
df["vehicle_id"].value_counts()

vehicle_id
VH002    212
VH004    207
VH003    205
VH001    203
VH005    173
Name: count, dtype: int64

In [48]:
df.groupby("vehicle_id")["engine_temperature"].mean()

vehicle_id
VH001    94.518719
VH002    94.958349
VH003    95.790829
VH004    94.204734
VH005    94.595549
Name: engine_temperature, dtype: float64

In [49]:
df[df["engine_temperature"] > 100]

,vehicle_id,timestamp,engine_temperature,battery_voltage,vibration,brake_temperature,speed,mileage,fault_code,maintenance_required
0,VH002,2026-09-08 09:00:00,107.52,11.90,3.01,87.31,50,33076,F000,Yes
1,VH003,2026-09-08 09:05:00,103.67,11.74,4.70,72.66,57,95784,F001,Yes
2,VH005,2026-09-08 09:10:00,106.75,11.50,4.05,91.00,99,31791,F001,Yes
5,VH005,2026-09-08 09:25:00,108.62,12.99,1.33,97.27,69,54895,F002,No
6,VH005,2026-09-08 09:30:00,104.97,12.62,1.61,109.94,82,81493,F001,Yes
...,...,...,...,...,...,...,...,...,...,...
986,VH004,2026-09-11 19:10:00,104.92,11.62,1.36,60.54,91,53507,F001,Yes
991,VH001,2026-09-11 19:35:00,101.77,12.84,1.99,69.12,49,67220,F000,No
994,VH003,2026-09-11 19:50:00,104.86,12.89,2.99,77.52,33,50471,F001,No
995,VH002,2026-09-11 19:55:00,101.84,11.61,7.02,64.44,82,55738,F000,Yes
999,VH002,2026-09-11 20:15:00,103.66,12.92,4.48,101.02,66,34698,F000,Yes

In [50]:
df[df["vibration"]> 7]

,vehicle_id,timestamp,engine_temperature,battery_voltage,vibration,brake_temperature,speed,mileage,fault_code,maintenance_required
17,VH001,2026-09-08 10:25:00,84.43,12.45,7.58,94.78,33,91301,F002,No
23,VH001,2026-09-08 10:55:00,82.57,11.78,7.80,62.26,82,60786,F001,Yes
24,VH004,2026-09-08 11:00:00,103.78,12.28,8.64,66.86,87,91570,F002,Yes
28,VH005,2026-09-08 11:20:00,104.79,12.37,7.87,100.78,38,96397,F000,Yes
31,VH005,2026-09-08 11:35:00,89.37,11.96,8.16,91.84,61,22139,F001,Yes
...,...,...,...,...,...,...,...,...,...,...
983,VH005,2026-09-11 18:55:00,87.82,12.03,8.54,106.72,50,35616,F002,Yes
985,VH004,2026-09-11 19:05:00,100.86,12.02,7.80,86.22,70,67092,F000,Yes
995,VH002,2026-09-11 19:55:00,101.84,11.61,7.02,64.44,82,55738,F000,Yes
997,VH004,2026-09-11 20:05:00,86.37,12.50,7.60,60.17,40,50208,F002,No
998,VH002,2026-09-11 20:10:00,96.67,12.42,7.10,99.87,53,37051,F002,No

In [51]:
df[df["battery_voltage"] < 12]

,vehicle_id,timestamp,engine_temperature,battery_voltage,vibration,brake_temperature,speed,mileage,fault_code,maintenance_required
0,VH002,2026-09-08 09:00:00,107.52,11.90,3.01,87.31,50,33076,F000,Yes
1,VH003,2026-09-08 09:05:00,103.67,11.74,4.70,72.66,57,95784,F001,Yes
2,VH005,2026-09-08 09:10:00,106.75,11.50,4.05,91.00,99,31791,F001,Yes
3,VH001,2026-09-08 09:15:00,92.06,11.96,6.02,67.53,98,23477,F001,No
4,VH002,2026-09-08 09:20:00,96.11,11.76,4.08,88.42,41,80012,F002,No
...,...,...,...,...,...,...,...,...,...,...
987,VH004,2026-09-11 19:15:00,98.86,11.55,4.83,103.89,50,54784,F001,Yes
990,VH003,2026-09-11 19:30:00,93.43,11.99,1.37,64.61,53,46852,F001,No
993,VH004,2026-09-11 19:45:00,80.46,11.63,5.27,82.51,23,62913,F000,No
995,VH002,2026-09-11 19:55:00,101.84,11.61,7.02,64.44,82,55738,F000,Yes
996,VH004,2026-09-11 20:00:00,93.96,11.78,4.40,98.13,42,74518,F002,No